name: Walls
Author: CuboidCat
version: '1.0'
main: com.cuboidcat.walls.Main
api-version: "1.20"
commands:
  walls:
    permission: walls.walls
  setteam:
    permission: walls.teams
  walldelete:
  wallsend: